services:
  - type: web
    name: EngagingReader
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 300"
    envVars:
      - key: GEMINI_API_KEY
        value: "{{.GEMINI_API_KEY}}"
      - key: GOOGLE_PROJECT
        value: "engaging-reader"
      - key: GOOGLE_LOCATION
        value: "us-central1"
      - key: FLASK_DEBUG
        value: "false"
      - key: PORT
        value: "10000"
      - key: GUNICORN_RUNNING
        value: "true"
    plan: starter
